// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmMNNYKP2f4qUEBothGxmgnw3egxhOIms',
    appId: '1:65399674922:web:fe0f5f1c74a0f56b1a8b53',
    messagingSenderId: '65399674922',
    projectId: 'akurasi-pupuk-app',
    authDomain: 'akurasi-pupuk-app.firebaseapp.com',
    storageBucket: 'akurasi-pupuk-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADIDbBMKahuU4CLIfGcdCG1eNdL8YQm48',
    appId: '1:65399674922:android:449ce9b834d6d7391a8b53',
    messagingSenderId: '65399674922',
    projectId: 'akurasi-pupuk-app',
    storageBucket: 'akurasi-pupuk-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx-IFp8JZmYhlV4Vy0tm8IuOMKz3Mkegs',
    appId: '1:65399674922:ios:4555970d34bd449c1a8b53',
    messagingSenderId: '65399674922',
    projectId: 'akurasi-pupuk-app',
    storageBucket: 'akurasi-pupuk-app.firebasestorage.app',
    iosClientId: '65399674922-jrg246evgmjk05eeqic9t6f8gqqs1h7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx-IFp8JZmYhlV4Vy0tm8IuOMKz3Mkegs',
    appId: '1:65399674922:ios:4555970d34bd449c1a8b53',
    messagingSenderId: '65399674922',
    projectId: 'akurasi-pupuk-app',
    storageBucket: 'akurasi-pupuk-app.firebasestorage.app',
    iosClientId: '65399674922-jrg246evgmjk05eeqic9t6f8gqqs1h7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfgApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmMNNYKP2f4qUEBothGxmgnw3egxhOIms',
    appId: '1:65399674922:web:131c3cb27df7096d1a8b53',
    messagingSenderId: '65399674922',
    projectId: 'akurasi-pupuk-app',
    authDomain: 'akurasi-pupuk-app.firebaseapp.com',
    storageBucket: 'akurasi-pupuk-app.firebasestorage.app',
  );

}